#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
DIR="$HOME/.config/i3"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/bsp-scripts/rofi_askpass

# execute the application
sudo -A $1
